version: '2'
jobs:
  build:
    working_directory: /go/src/github.com/qri-io/cafs
    docker:
      - image: circleci/golang:1.11
        environment:
          GOLANG_ENV: test
          PORT: 3000
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: 
          name: Install test deps
          command: >
            go get -v
            github.com/jstemmer/go-junit-report 
            github.com/golang/lint/golint
            github.com/whyrusleeping/gx 
            github.com/whyrusleeping/gx-go 
      - run:
          name: Install non-gx deps
          command: >
            go get -t -d -v 
            github.com/ipfs/go-datastore
            github.com/jbenet/goprocess
            github.com/satori/go.uuid
            github.com/jbenet/go-base58
            github.com/multiformats/go-multihash
            github.com/spaolacci/murmur3
            golang.org/x/crypto/blake2b
            cloud.google.com/go/storage
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install gx deps
          command: gx install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - /go/src/gx/
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            ./.circleci/cover.test.sh | tee ${TEST_RESULTS}/go-test.out
      - run:
          name: Publish coverage info to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results